character_data = {
"name": "Bob",
"base_health": 30,
"base_attack": 30,
"base_defence": 30,
"has_ring": False,
"ring_health": 1,
"has_necklace": False,
"necklace_health": 0,
"has_shield": False,
"shield_health": 0,
"has_sword1": False,
"sword_1_attack": 0,
"has_sword2": False,
"sword_2_attack": 0,
"has_sword3": False,
"sword_3_attack": 0,
"max_sword_attack": 0,
"has_key": False,
"current_health": 30,
"current_attack": 30,
"current_defence": 30
}


scene_1 = {
"scene_title":"Prison Cell",
"scene_description": "You awaken in a dark cell, head throbbing and body aching from the battle earlier that day. \n You hear soft footsteps outside, a short silence before a click as the lock is turned. The door opens to reveal your mother, the queen in a dark robe. She stealthily moves towards you and whispers, Bob Thank god you are OK! Come with me quickly, we don't have much time.",
"option_1_text": "Immediately exit the cell with her",
"option_1_function": "Load_scene",
"option_1_function_text": "scene_2",
"option_1_display": True,
"option_2_text": "Ask, 'We lost? Is Jennifer safe?",
"option_2_function": "display-message",
"option_2_function_text": "We did... I'm sorry Bob... That tyrant, Archibald took her'. Footsteps then the door flings open! Guards enter and the captain gives the orders, 'Take that slag to a cell, we\'ll have fun with her later... And slit that pricks throat!",
"option_2_display": True,
"option_3_text": "Do Nothing",
"option_3_function": "",
"option_3_display": True,
"option_4_text": "should not display",
"option_4_function": "",
"option_4_display": False,
"enemy_exists": False,
"enemy_alive": False,
"enemy_name": "ogre",
"enemy_health": 5,
"enemy_attack": 5,
"enemy_defence": 5,
"chest_exists": "",
"chest_contents_name": "",
"chest_full": "",
"riddle_text": "",
"riddle_answer": "",
"success": "",
"success_text": "",
"success_function_name": "" }


