character_data = {
    "current_scene": "scene_1",
    "name": "Errenwulf",
    "dead": False,
    "base_health": 20,
    "base_attack": 20,
    "base_defence": 20,
    "has_ring": False,
    "ring_health": 1,
    "has_necklace": False,
    "necklace_health": 0,
    "has_shield": False,
    "shield_health": 0,
    "has_sword1": False,
    "sword_1_attack": 0,
    "has_sword2": False,
    "sword_2_attack": 0,
    "has_sword3": False,
    "sword_3_attack": 0,
    "max_sword_attack": 0,
    "has_key": False,
    "current_health": 20,
    "current_attack": 20,
    "current_defence": 20
}